
create table user (
	id bigint generated by default as identity,
	alias_name varchar(64) not null,
	login_name varchar(64) not null unique,
	salt varchar(64) not null,
	email varchar(128),
	hash_password varchar(255) not null,
	primary key (id)
);

create table role (
	id bigint generated by default as identity,
	role_alias_name varchar(128) not null,
	role_name varchar(64) not null unique,
	primary key (id)
);

create table user_role (
	user_id bigint not null,
  role_id bigint not null,
	primary key (user_id, role_id)
);

create table url_filter (
  id bigint generated by default as identity,
  name varchar(100) not null,
	url varchar(100) not null,
	basics varchar(100),
	roles varchar(100),
	permissions varchar(100),
	primary key (id)
);

insert into user (id,email,alias_name,login_name,salt,hash_password) values(1,'linchao@111.com.cn','张三','yyw01','b6682f6ff51ca51e','eea645f601a395e800163c89d18241a060a2d826');
insert into user (id,email,alias_name,login_name,salt,hash_password) values(2,'c.lins@qq.com','李四','yyw02','b6446157e322ef03','1f0914cf5a3e2cdb9e0b9252e8d607deddafcb50');

insert into role (id,role_alias_name,role_name) values(1,'系统管理员','system');
insert into role (id,role_alias_name,role_name) values(2,'超级管理员','admin');
insert into role (id,role_alias_name,role_name) values(3,'日志管理员','log');

insert into user_role (user_id,role_id) values(1,1);
insert into user_role (user_id,role_id) values(2,2);
insert into user_role (user_id,role_id) values(2,3);

insert into url_filter (id,name,url,basics,roles,permissions) values(1,'url测试1','/v1/account/text','authc','system',null);
--insert into url_filter (id,name,url,basics,roles,permissions) values(2,'url测试2','/v1/account/text','ssl',null,null);
