# Server settings
server:
    port: 8080
#    context-path: / by default
management:
    port: 7002

# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    # SPRING MVC (HttpMapperProperties)
    mvc.view:
        prefix: /WEB-INF/views/
        suffix: .html
    # DATASOURCE
    #set H2 in file mode as the production DB
    jpa:
        database: H2
        hibernate:
            ddl-auto: none
    datasource:
        driverClassName: org.h2.Driver
#        url: jdbc:h2:file:~/.h2/bootapi;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;
        url: jdbc:h2:mem:bootapi_mem
        username: sa
        password:
        initialize: false
        initial-size: 10
        max-active: 100
        min-idle: 8
        max-idle: 8

flyway:
    enabled: true

# MyBatis
#mybatis:
#    typeAliasesPackage: com.fangkuaiyi.visit.bo
#    mapperLocations: classpath:/mybatis/*Mapper.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG
