# Server settings
server:
    port: 8080

# DATASOURCE
jdbc:
    driverClass: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.16.3.8:1521:YaoOracle
    username: b2bvimprod
    password: 8xeOt9#yTH
    validationQuery: select 1 from dual
    testWhileIdle: true

# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    # SPRING MVC (HttpMapperProperties)
    view:
        prefix: /WEB-INF/views/
        suffix: .html

# MyBatis
mybatis:
    typeAliasesPackage: com.fangkuaiyi.visit.bo
    mapperLocations: classpath:/mybatis/*Mapper.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG
